font_family JetBrainsMono Nerd Font
font_size 14

include ./Forest Night.conf

# Shell integration is sourced and configured manually
shell_integration no-rc

active_border_color #a9dd9d
# background_blur 100
# background_opacity 0.90
background_image ../walls/rose-pine1-adj.png
background_image_layout cscaled
background_tint 0.9
background_image_linear yes
copy_on_select clipboard
cursor_trail 200
cursor_trail_color #f0aa8a
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2
dynamic_background_opacity yes
hide_window_decorations no
inactive_border_color #005757
mouse_hide_wait -3.000000
scrollback_pager nvim -c 'set ft=log' -
shell /nix/store/10j6f5gdmz30v9fvyc2d4igkmra4g105-fish-4.1.2/bin/fish
tab_bar_style powerline
tab_powerline_style slanted
window_border_width 1
window_padding_width 10

allow_remote_control yes

enabled_layouts splits,stack
map ctrl+, toggle_layout stack
map ctrl+[ previous_window
map ctrl+] next_window

map ctrl+/ launch --cwd=current --location=split

# Pane focus, integrated with vim-kitty-navigation support
map ctrl+j kitten pass_keys.py bottom ctrl+j
map ctrl+k kitten pass_keys.py top    ctrl+k
map ctrl+h kitten pass_keys.py left   ctrl+h
map ctrl+l kitten pass_keys.py right  ctrl+l
# listen_on unix:@mykitty # Linux only
listen_on unix:/tmp/mykitty


map ctrl+shift+p kitten print_procs.py

