#!/bin/bash
options=(
  style=round
  width=5.0
  hidpi=on
  active_color=0xff74fff8
  inactive_color=0xff387c79
  background_color=0x000000
  ax_focus=on
  blacklist="Leader Key"
)

borders "${options[@]}"
